config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'

  }

  resources :genres
  resources :events
  resources :purposes
  resources :scores
  resources :post_times
  resources :users
  resources :media
  resources :contacts do
    resources :contact_comments
  end
  resources :studies do
    resource :likes, only: [:create, :destroy]
    resources :study_comments, only: [:create, :destroy]
  end





  namespace :admin do
    resources :events
    resources :users
    resources :purposes
    resources :genres
    resources :media
    resources :studies do
    resources :study_comments, only: [:destroy]
  end
    resources :contacts do
      resources :contact_comments
    end
  end
  root to: 'studies#index'
  get 'about' => 'studies#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name,uniqueness: true ,length: { minimum: 2 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :studies, dependent: :destroy
  has_many :scores, dependent: :destroy
  has_many :purposes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_studies, through: :likes, source: :study
  has_many :contacts, dependent: :destroy
  has_many :post_times, dependent: :destroy
  attachment :profile_image
  has_many :study_comments, dependent: :destroy

  accepts_nested_attributes_for :scores, :purposes

  def already_liked?(study)
    self.likes.exists?(study_id: study.id)
  end

  def usertime
                     if scores.last.current_score < 201
                        0
                     elsif scores.last.current_score < 251
                        200
                     elsif scores.last.current_score < 301
                        400
                     elsif scores.last.current_score < 351
                        600
                     elsif scores.last.current_score < 401
                        800
                     elsif scores.last.current_score < 451
                        950
                     elsif scores.last.current_score < 501
                        1100
                     elsif scores.last.current_score < 551
                        1250
                     elsif scores.last.current_score < 601
                        1400
                     elsif scores.last.current_score < 651
                        1550
                     elsif scores.last.current_score < 701
                        1700
                     elsif scores.last.current_score < 751
                        2000
                     elsif scores.last.current_score < 801
                        2300
                     elsif scores.last.current_score < 851
                        2600
                     elsif scores.last.current_score < 901
                        2900
                     elsif scores.last.current_score < 951
                        3400
                     else
                        3900
                     end

  end

  def purposetime
                     if purposes.last.purpose_score < 201
                        0
                     elsif purposes.last.purpose_score < 251
                        200
                     elsif purposes.last.purpose_score < 301
                        400
                     elsif purposes.last.purpose_score < 351
                        600
                     elsif purposes.last.purpose_score < 401
                        800
                     elsif purposes.last.purpose_score < 451
                        950
                     elsif purposes.last.purpose_score < 501
                        1100
                     elsif purposes.last.purpose_score < 551
                        1250
                     elsif purposes.last.purpose_score < 601
                        1400
                     elsif purposes.last.purpose_score < 651
                        1550
                     elsif purposes.last.purpose_score < 701
                        1700
                     elsif purposes.last.purpose_score < 751
                        2000
                     elsif purposes.last.purpose_score < 801
                        2300
                     elsif purposes.last.purpose_score < 851
                        2600
                     elsif purposes.last.purpose_score < 901
                        2900
                     elsif purposes.last.purpose_score < 951
                        3400
                     else
                        3900
                     end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
        @user = User.find(params[:id])
        @post_time = PostTime.new
        @totalstudytime =  @user.post_times.all.sum(:study_time)
                            respond_to do |format|
                            format.html
                            format.json {render:json => @totalstudytime}
                            format.js
                            end

        @usertime =  @user.usertime
                     respond_to do |format|
                     format.html
                     format.json {render:json => @usertime}
                     format.js
                     end

        @purposetime =  @user.purposetime
                     respond_to do |format|
                     format.html
                     format.json {render:json => @purposetime}
                     format.js
                     end
        @post_times = @user.post_times.order(study_day: "DESC").page(params[:page]).per(6)
        @graphtimes =  @user.post_times.order(study_day: "DESC").limit(6).reverse
        @timeline = Array.new
        @graphtimes.each do |graphtime|
            @timeline.push(graphtime.study_time)
        end
        @graphdays =  @user.post_times.order(study_day: "DESC").limit(6).reverse
        @dayline = Array.new
        @graphdays.each do |graphday|
            @dayline.push(graphday.study_day.strftime('%m/%d').to_s)
        end

    end

    def index
         user_time_count = User.all.joins(:post_times).where(post_times:{ study_day:1.weeks.ago..Time.now}).group(:user_id).sum(:study_time)
         user_time_ids = Hash[user_time_count.sort_by{ |_, v| -v }].keys
         @user_ranking= User.find(user_time_ids).sort_by{ |o| user_time_ids.index(o.id)}
         @users = User.all
    end

    def edit
        @user = User.find(params[:id])
        if @user.id != current_user.id
            redirect_to user_path(@current_user.id)
        end
    end

    def update
        user = User.find(params[:id])
        user.update(user_params)
        redirect_to user_path(user.id)
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to root_path

    end

  private

    def user_params
        params.require(:user).permit(:name,:profile_image)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
     super
     User.last.scores.create
     User.last.purposes.create
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     new_purpose_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :authenticate_user!

  def show
        @user = User.find(params[:id])
        @post_time = PostTime.new
        @totalstudytime =  @user.post_times.all.sum(:study_time)
                            respond_to do |format|
                            format.html
                            format.json {render:json => @totalstudytime}
                            format.js
                            end
        @allstudytime = @user.post_times.with_deleted.all.sum(:study_time)

        @usertime =  @user.usertime
                     respond_to do |format|
                     format.html
                     format.json {render:json => @usertime}
                     format.js
                     end

        @purposetime =  @user.purposetime
                     respond_to do |format|
                     format.html
                     format.json {render:json => @purposetime}
                     format.js
                     end
        @post_times = @user.post_times.with_deleted.order(study_day: "DESC").page(params[:page]).per(6)
        @graphtimes =  @user.post_times.with_deleted.order(study_day: "DESC").limit(6).reverse
        @timeline = Array.new
        @graphtimes.each do |graphtime|
            @timeline.push(graphtime.study_time)
        end
        @graphdays =  @user.post_times.with_deleted.order(study_day: "DESC").limit(6).reverse
        @dayline = Array.new
        @graphdays.each do |graphday|
            @dayline.push(graphday.study_day.strftime('%m/%d').to_s)
        end

    end

    def index
         user_time_count = User.all.joins(:post_times).where(post_times:{ study_day:1.weeks.ago..Time.now}).group(:user_id).sum(:study_time)
         user_time_ids = Hash[user_time_count.sort_by{ |_, v| -v }].keys
         @user_ranking= User.find(user_time_ids).sort_by{ |o| user_time_ids.index(o.id)}
         @users = User.all
    end

    def edit
        @user = User.find(params[:id])
        if @user.id != current_user.id
            redirect_to user_path(@current_user.id)
        end
    end

    def update
        user = User.find(params[:id])
        user.update(user_params)
        redirect_to user_path(user.id)
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to root_path

    end

  private

    def user_params
        params.require(:user).permit(:name,:profile_image)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_list.html.erb
<table>
      <tbody>
        <% @post_times.each do |time| %>
        <tr>
            <td class="align-middle"><%= time.study_day%></td>
          <td class="align-middle"><%= time.study_time %>時間</td>
        </tr>
        <% end %>
      </tbody>
</table>

app/views/users/edit.html.erb
  <div class="container"style="padding: 20px;">
      <div class="row">
        <div class="col-3">
        </div>
        <div class="col-5">
           <%= form_for(@user) do |f| %>
           <table  border="1" bordercolor="#4682B4" cellpadding="15" style="width:100%; border-collapse:separate;margin-top: 50px;">
            <tr><td colspan="2"><h2>ユーザー編集</h2></td></tr>
              <tr>
                <th style = "width:30%"><%= f.label :"名前" %></th>
                <td style = "width:70%"><%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control" %></td>
              </tr>

              <tr>
                <th><%= f.label :"画像" %></th>
                <td> <%= f.attachment_field :profile_image %></td>
              </tr>

            <tr>
              <td colspan="2"><%= f.submit "変更", class: "btn btn-primary btn-block" %></td>
            </tr>
        </table>
      <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<div class="week_ranking">
  <div class="container">
    <div class="row">
      <div class="col-8">
          <h2 class="user_ranking">週間学習時間ランキング</h2>
            <table class="table table-striped">
               <thead>
                  <tr>
                    <th>Ranking</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Time</th>
                 </tr>
              </thead>
                <tbody>
                  <% @user_ranking.each_with_index do |u,i| %>
                    <tr>
                      <td><%= i  + 1 %></td>
                      <td><%= attachment_image_tag u, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image2.jpg", size: '60x60' %></td>
                      <td class="align-middle"><%= link_to u.name, user_path(u.id) %></td>
                      <td class="align-middle"><%= u.post_times.where(study_day:1.weeks.ago..Time.now).sum(:study_time) %>時間</td>
                   </tr>
                 <% end %>
              </tbody>
            </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="mypage">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card" style="text-align: center">
          <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: 'jpeg',fallback: "no_image2.jpg", size: '255x255'%>
          <%= @user.name %>
            <div class="card-body">
              <div>目標スコア: <%= @user.purposes.last.purpose_score %>点</div>
              <div>現在スコア: <%= @user.scores.last.current_score %>点</div>
               <div>目標時間: <%= @purposetime -  @usertime %>時間</div>
              <canvas id="myChart" width="200" height="200"></canvas>
              <script>
                var totalstudytime = <%= @totalstudytime %>, usertime = <%= @usertime %>,purposetime = <%= @purposetime %>
              </script>
              <script>draw_graph1();</script>
              <% if @user.id == current_user.id %>
                      <div> <%= link_to "スコアの変更", new_purpose_path, class:"btn-sm btn-primary btn-block" %></div>
                      <div><%= link_to "編集", edit_user_path(@user.id), class:"btn-sm btn-success btn-block" %></div>
                      <div><%= link_to "学習時間をリセット", post_time_path, class:"btn-sm btn-warning btn-block", method: :delete , "data-confirm" => "本当にリセットしますか？" %></div>
                      <div><%= link_to "退会", user_path(@user), class:"btn-sm btn-danger btn-block", method: :delete , "data-confirm" => "本当に退会しますか？" %>
                      </div>
                      <% end %>
            </div>
        </div>
      </div>


      <div class="col-9">
          <h2 class="mypage_index">最近の学習状況</h2>
            <div class="main clearfix">
              <div class="studygarph">
                 <canvas id="studyChart" width="200" height="200"></canvas>
                  <script>
                    var graphdays = <%== @dayline %>, graphtimes = <%= @timeline %>
                  </script>
                  <script>draw_graph2();</script>
              </div>
                <div class="studydate ">
                  <h4 class="total">総学習時間: <%= @allstudytime %>時間</h4>
                  <% if @user.id == current_user.id %>
                    <%= form_for(@post_time) do |f| %>
                    <label class="control-label" for="">勉強日</label>
                    <%= f.date_select(:study_day,use_month_numbers: true,default: Date.today) %>
                    <div class="form-group">
                     <%= f.label :"時間を追加" %>
                      <%= f.select(:study_time,  [-5,-4.5,-4,-3.5,-3,-2.5,-2,-1.5,-1,-0.5,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5.5,6,6.5,7,7.5,8,8.5,9,9.5,10],:selected=>1 )%>
                      <%= f.submit '追加する' %>
                   </div>
                   <% end %>
                      <% end %>
                  <div id="user_lists"><%= render 'user_list' %></div>
                   <% if @user.id == current_user.id %>
                      <div class="more"><%= link_to_next_page @post_times, 'もっと見る', remote: true, id: 'view_more' %></div>
                    <% end %>
                </div>
            </div>

             <h3 class="mypage_index">投稿内容</h3>
            <div class= "row" >
              <% @user.studies.each do |study| %>
              <div class= "col-2" >
                <div class = "mb-3 card"style="width: 100px;">
                <%= attachment_image_tag study, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100'%>
                <%= link_to study.study_title, study_path(study.id) %>
            </div>
          </div>
              <% end %>
          </div>

          <h3 class="mypage_index">いいねしている投稿</h3>
            <div class= "row" >
              <% @user.liked_studies.each do |study| %>
              <div class= "col-2" >
                <div class = "mb-3 card"style="width: 100px;">
                <%= attachment_image_tag study, :image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"%>
                <%= link_to study.study_title, study_path(study.id) %>
            </div>
          </div>
              <% end %>
              </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$('#user_lists').append("<%= escape_javascript(render 'user_list', object: @post_times) %>");
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@post_times, 'もっと見る', remote: true, id: 'view_more')) %>");