config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'

  }

  resources :genres
  resources :events
  resources :purposes
  resources :scores
  resources :post_times
  resources :users
  resources :media
  resources :contacts do
    resources :contact_comments
  end
  resources :studies do
    resource :likes, only: [:create, :destroy]
    resources :study_comments, only: [:create, :destroy]
  end





  namespace :admin do
    resources :events
    resources :users
    resources :purposes
    resources :genres
    resources :media
    resources :studies do
    resources :study_comments, only: [:destroy]
  end
    resources :contacts do
      resources :contact_comments
    end
  end
  root to: 'studies#index'
  get 'about' => 'studies#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/study.rb
class Study < ApplicationRecord
 validates :study_title,uniqueness: true ,length: { minimum: 2 }

belongs_to :user
belongs_to :genre
belongs_to :medium
attachment :image
has_many :likes
has_many :liked_users, through: :likes, source: :user
has_many :study_comments, dependent: :destroy

end

app/controllers/admin/studies_controller.rb
class Admin::StudiesController < ApplicationController
  before_action :authenticate_admin!
	def show
    @study = Study.find(params[:id])
    @study_comments = @study.study_comments
  end

  def index
    @studies = Study.all
  end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    redirect_to admin_studies_path
  end

  private
  
    def study_params
        params.require(:study).permit(:study_title, :review)
    end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @study = Study.find(params[:id])
    @like = Like.new
    @study_comments = @study.study_comments
    @study_comment = StudyComment.new
  end

  def index
    @studies = Study.page(params[:page]).per(6).order(id: "DESC")
    @search = Study.ransack(params[:q])
    @studies = @search.result.page(params[:page]).per(6).order(id: "DESC")
    @all_ranks = Study.find(Like.group(:study_id).order('count(study_id) desc').limit(5).pluck(:study_id))
    @like = Like.new
  end

  def new
    @study = Study.new
  end

  def create
    @study = Study.new(study_params)
    @study.user_id = current_user.id
    @study.save
    redirect_to root_path
  end

  def edit
     @study = Study.find(params[:id])
  end

  def update
    study = Study.find(params[:id])
    study.update(study_params)
    redirect_to study_path(study.id)
  end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    redirect_to root_path
  end

  def correct_user
    @study = Study.find(params[:id])
    if current_user.id != @study.user_id
      redirect_to root_path
    end
  end

  def about
  end

  private
  
    def study_params
        params.require(:study).permit(:study_title, :review, :image, :user_id, :genre_id, :medium_id)
    end
end

app/helpers/admin/studies_helper.rb
module Admin::StudiesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/about.html.erb
<div class="study_page"style="padding: 50px">
  <div class="container">
    <div class="row">
      <div class="col-2">
      </div>
      <div class="col-10">
       <h2>このアプリはTOEIC学習に関する勉強方法の共有</h2><br>
       <h2>ユーザーの学習計画の作成、学習時間の管理を</h2><br>
       <h2>お手伝いをすることを目的としたアプリです。</h2><br>
       <h2>このアプリにおいて、目標達成のための時間が</h2><br>
       <h2>表示されますが、目安としての時間として</h2><br>
       <h2>参考程度にして頂くようお願い致します。</h2><br>
       <h2>勉強方法共有のため、使っている本、アプリが</h2><br>
       <h2>投稿されていましたら、いいねをお願い致します。</h2><br>

      </div>
  </div>
</div>
</div>

app/views/studies/edit.html.erb
  <div class="container"style="padding: 20px;">
      <div class="row">
        <div class="col-3">
        </div>
        <div class="col-6">
                <%= form_for(@study) do |f| %>
               <table  border="1" bordercolor="#4682B4" cellpadding="15" style="width:100%; border-collapse:separate;margin-top: 50px;">
              <tr><td colspan="2"><h2>編集</h2></td></tr>
              <tr>
                  <th style = "width:40%"><%= f.label :"画像" %></th>
                  <td style = "width:60%"><%= f.attachment_field :image %></td>
              </tr>

              <tr>
                  <th><%= f.label :"タイトル" %></th>
                  <td><%= f.text_field :study_title, class: "form-control" %></td>
              </tr>

                <tr>
                  <th><%= f.label :"媒体" %></th>
                   <td><%=  f.collection_select :medium_id, Medium.all, :id, :medium_name, :prompt => "媒体(本やアプリなど)を選択してください", class: "select" %></td>
               </tr>

               <tr>
                  <th><%= f.label :"ジャンル" %></th>
                 <td><%=  f.collection_select :genre_id, Genre.all, :id, :genre_name, :prompt => "ジャンルを選択してください", class: "select" %></td>
               </tr>

              <tr>
                  <th><%= f.label :"本文" %></th>
                 <td><%= f.text_area :review, class: "form-control"%></td>
               </tr>

            <tr>
              <td colspan="2"><%= f.submit "編集", class: "btn btn-primary btn-block" %></td>
            </tr>
        </table>
      <% end %>
      </div>
      </div>
  </div>

app/views/studies/index.html.erb
<div class="study_page">
  <div class="container">
    <div class="row">
      <div class="col-3">
          <div class="card " >
            <% if user_signed_in? %>
                <span><%= link_to "新規投稿をする。", new_study_path,class:'btn btn-primary btn-lg btn-block' %></span>
            <%else%>
              <h3 class="btn btn-info">いいねランキング</h3>
                <% end %>
            <div class="card-body">
                <% @all_ranks.each do |r| %>
                   <div class="row">
                      <div class="col-4">
                         <%= link_to (study_path(r.id)) do %>
                         <%= attachment_image_tag r, :image, :fill, 70, 70, format: 'jpeg', fallback: "/images/no_image.jpg" %>
                         <% end %>
                      </div>
                      <div class="col-8">
                          <table class="table" >
                            <tr>
                              <th><%= truncate(r.study_title, length: 7, :omission => "...") %></th>
                            </tr>
                            <tr>
                              <td>
                                <% if user_signed_in? %>
                                    <% if current_user.already_liked?(r) %>
                                      <%= link_to study_likes_path(r), method: :delete do %>
                                        <i class="fas fa-thumbs-up"style="font-size: 20px;"></i> <%= r.liked_users.count %>
                                      <% end %>
                                    <% else %>
                                      <%= link_to study_likes_path(r), method: :post do %>
                                         <i class="far fa-thumbs-up" style="font-size: 20px;"></i> <%= r.liked_users.count %>
                                     <% end %>
                                  <% end %>
                                  <% else %>
                                  <%= r.liked_users.count %>いいね
                                <% end %>
                            </td>
                            </tr>
                          </table>
                    </div>
                  </div>
                <% end %>
          </div>
         </div>
      </div>

      <div class="col-9 study_box">
        <div class="title">
          <h1 class="study_title">レビュー 一覧</h1>
            <%= search_form_for @search do |f| %>
              <%= f.search_field :study_title_or_review_or_medium_medium_name_or_genre_genre_name_cont_any %>
              <%= f.submit "検索" %>
  　         <% end %>
        </div>

          <ul class="study-list jscroll">
            <div class="container study_box clearfix" >
                <% @studies.each do |s| %>
              <div class="float-left index_studies">
                <div class="row">
                  <div class ="col">
                     <div class="card" style="margin: 20px;">
                         <%= link_to (study_path(s.id)) do %>
                          <%= attachment_image_tag s, :image, :fill, 200, 200, format: 'jpeg', fallback: "/images/no_image.jpg",class: "img-fluid" %>
                          <% end %>
                        <div class="card-body">
                          <div><%= truncate(s.study_title, length: 12, :omission => "...") %></div>
                            <div><%= s.medium.medium_name %></div>
                            <div><%= s.genre.genre_name %></div>
                            <div>
                             <% if user_signed_in? %>
                                <% if current_user.already_liked?(s) %>
                                 <%= link_to study_likes_path(s), method: :delete do %>
                                  <i class="fas fa-thumbs-up"style="font-size: 20px;"></i> <%= s.liked_users.count %>
                                 <% end %>
                                <% else %>
                                 <%= link_to study_likes_path(s), method: :post do %>
                                  <i class="far fa-thumbs-up" style="font-size: 20px;"></i> <%= s.liked_users.count %>
                                 <% end %>
                                <% end %>
                                <% else %>
                                  <%= s.liked_users.count %>いいね
                             <% end %>
                            </div>
                        </div>
                   </div>
                  </div>
                </div>
              </div>
              <% end %>
          </div>
              <%= paginate @studies %>
        </ul>
            <div id="smooth-scroll">  <%= image_tag '/images/image4.png'%></div>
    </div>
  </div>
</div>

app/views/studies/new.html.erb
<div class="body">
  <div class="container"style="padding: 20px;">
      <div class="row">
        <div class="col-3">
        </div>
        <div class="col-6">
               <%= form_for(@study) do |f| %>
               <table  border="1" bordercolor="#4682B4" cellpadding="15" style="width:100%; border-collapse:separate;margin-top: 50px;">
              <tr><td colspan="2"><h2>新規投稿</h2></td></tr>
              <tr>
                  <th style = "width:40%"><%= f.label :"画像" %></th>
                  <td style = "width:60%"><%= f.attachment_field :image %></td>
              </tr>

              <tr>
                  <th><%= f.label :"タイトル" %></th>
                  <td><%= f.text_field :study_title, class: "form-control" %></td>
              </tr>

                <tr>
                  <th><%= f.label :"媒体" %></th>
                  <td><%=  f.collection_select :medium_id, Medium.all, :id, :medium_name, :prompt => "媒体(本やアプリなど)を選択してください", class: "select" %></td>
               </tr>

               <tr>
                  <th><%= f.label :"ジャンル" %></th>
                 <td><%=  f.collection_select :genre_id, Genre.all, :id, :genre_name, :prompt => "ジャンルを選択してください", class: "select" %></td>
               </tr>

              <tr>
                  <th><%= f.label :"本文" %></th>
                 <td><%= f.text_area :review, class: "form-control"%></td>
               </tr>

            <tr>
              <td colspan="2"><%= f.submit "投稿", class: "btn btn-primary btn-block" %></td>
            </tr>
        </table>
      <% end %>
      </div>
      </div>
  </div>
</div>

app/views/studies/show.html.erb
<div class="study_detail">
  <div class="container">
      <div class="row">
        <div class="col-4">
          <%= attachment_image_tag @study, :image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg" %>
            <h5 class="reviewer">レビュアー　 <%= link_to @study.user.name, user_path(@study.user.id) %></h5>
        </div>
        <div class="col-5">
              <h4 class="detail_title">タイトル</h4>
                  <h5 class="detail_body"><%= @study.study_title %></h5>
              <h4 class="detail_title">媒体</h4>
                  <h5 class="detail_body"><%= @study.medium.medium_name %></h5>
              <h4 class="detail_title">ジャンル</h4>
                  <h5 class="detail_body"><%= @study.genre.genre_name %></h5>
              <h4 class="detail_title">本文</h4>
                  <h5 class="detail_body"><%= @study.review %></h5>
              <h4 class="detail_title">いいね件数: <%= @study.likes.count %></h4>
               <% if user_signed_in? %>
                  <% if current_user.already_liked?(@study) %>
                   <%= link_to study_likes_path(@study), method: :delete do %>
                          <i class="fas fa-thumbs-up"style="font-size: 20px;">いいねを取り消す</i>
                          <% end %>
                            <% else %>
                       <%= link_to study_likes_path(@study), method: :post do %>
                     <i class="far fa-thumbs-up" style="font-size: 20px;"> いいね！</i>
                       <% end %>
                  <% end %>
              <% end %>
               <%= form_for [@study, @study_comment] do |f| %>
                 <%= f.text_field :comment %><br>
                 <%= f.submit 'コメントする' %>
               <% end %>
                <table class="table table-striped">
                  <h4 class="detail_title">コメント一覧</h4>
                   <tbody>
                     <% @study_comments.each do |c| %>
                    <tr>
                    <td><div>
                           <%= link_to (user_path(c.id)) do %>
                           <%= attachment_image_tag c.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                           <% end %>
                        </div>
                           <%= link_to (c.user.name), user_path(c.user.id) %>
                     </td>
                      <td> <%= c.comment %></td>
                       <% if user_signed_in? && c.user_id == current_user.id %>
                      <td><%= link_to "削除", study_study_comment_path(@study,c), class: "btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？"%><td>
                        <% end %>
                   </tr>
                 <% end %>
                  </tbody>
                 </table>

                  <div>
                   <% if user_signed_in? && @study.user_id == current_user.id %>
                   <%= link_to "編集", edit_study_path(@study) %>
                   <%= link_to "削除", study_path(@study), method: :delete, "data-confirm" => "本当に消しますか？" %>
                   <% end %>
                 </div>
		    </div>
	   </div>
  </div>
</div>