config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
   :registrations => 'users/registrations'
  }

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'

  }

  resources :genres
  resources :events
  resources :purposes
  resources :scores
  resources :post_times
  resources :users
  resources :media
  resources :contacts do
    resources :contact_comments
  end
  resources :studies do
    resource :likes, only: [:create, :destroy]
    resources :study_comments, only: [:create, :destroy]
  end





  namespace :admin do
    resources :events
    resources :users
    resources :purposes
    resources :genres
    resources :media
    resources :studies do
    resources :study_comments, only: [:destroy]
  end
    resources :contacts do
      resources :contact_comments
    end
  end
  root to: 'studies#index'
  get 'about' => 'studies#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/study.rb
class Study < ApplicationRecord
 validates :study_title,uniqueness: true ,length: { minimum: 2 }

belongs_to :user
belongs_to :genre
belongs_to :medium
attachment :image
has_many :likes
has_many :liked_users, through: :likes, source: :user
has_many :study_comments, dependent: :destroy

end

app/controllers/admin/studies_controller.rb
class Admin::StudiesController < ApplicationController
  before_action :authenticate_admin!
	def show
    @study = Study.find(params[:id])
    @study_comments = @study.study_comments
  end

  def index
    @studies = Study.all
  end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    redirect_to admin_studies_path
  end

  private
  
    def study_params
        params.require(:study).permit(:study_title, :review)
    end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @study = Study.find(params[:id])
    @like = Like.new
    @study_comments = @study.study_comments
    @study_comment = StudyComment.new
  end

  def index
    @studies = Study.page(params[:page]).per(6).order(id: "DESC")
    @search = Study.ransack(params[:q])
    @studies = @search.result.page(params[:page]).per(6).order(id: "DESC")
    @all_ranks = Study.find(Like.group(:study_id).order('count(study_id) desc').limit(5).pluck(:study_id))
    @like = Like.new
  end

  def new
    @study = Study.new
  end

  def create
    @study = Study.new(study_params)
    @study.user_id = current_user.id
    @study.save
    redirect_to root_path
  end

  def edit
     @study = Study.find(params[:id])
  end

  def update
    study = Study.find(params[:id])
    study.update(study_params)
    redirect_to study_path(study.id)
  end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    redirect_to root_path
  end

  def correct_user
    @study = Study.find(params[:id])
    if current_user.id != @study.user_id
      redirect_to root_path
    end
  end

  def about
  end

  private
  
    def study_params
        params.require(:study).permit(:study_title, :review, :image, :user_id, :genre_id, :medium_id)
    end
end

app/helpers/admin/studies_helper.rb
module Admin::StudiesHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/admin/studies/index.html.erb
<h1>投稿一覧</h1>
  <table class="table table-striped">
  <thead>
    <tr>
      <th> Image</th>
      <th> Title</th>
      <th> Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @studies.each do |s| %>

    <tr>

      <td>
       <div>
        <%= attachment_image_tag s, :image, :fill, 50, 50, format: 'jpeg', fallback: "/images/no_image.jpg",size: '50x50' %>
       </div>
      </td>
      <td><%= link_to s.study_title, admin_study_path(s.id) %></td>
      <td><%= s.review %></td>

    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/studies/show.html.erb
<div class="studydetail">
  <div class="container">
      <div class="row">
        <div class="col-4">
          <%= attachment_image_tag @study, :image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg" %>
            <h5 class="reviewer">レビュアー　 <%= link_to @study.user.name, user_path(@study.user.id) %></h5>
        </div>
        <div class="col-5">
              <h4 class="detailtitle">タイトル</h4>
                  <h5 class="detailbody"><%= @study.study_title %></h5>
              <h4 class="detailtitle">媒体</h4>
                  <h5 class="detailbody"><%= @study.medium.medium_name %></h5>
              <h4 class="detailtitle">ジャンル</h4>
                  <h5 class="detailbody"><%= @study.genre.genre_name %></h5>
              <h4 class="detailtitle">本文</h4>
                  <h5 class="detailbody"><%= @study.review %></h5>
              <h4 class="detailtitle">いいね件数: <%= @study.likes.count %></h4>
                <table class="table table-striped">
                  <h4 class="detailtitle">コメント一覧</h4>
                   <tbody>
                     <% @study_comments.each do |c| %>
                    <tr>
                    <td><div>
                           <%= link_to (user_path(c.id)) do %>
                           <%= attachment_image_tag c.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
                           <% end %>
                        </div>
                           <%= link_to (c.user.name), user_path(c.user.id) %>
                     </td>
                      <td> <%= c.comment %></td>
                      <td><%= link_to "削除", admin_study_study_comment_path(@study,c), class: "btn btn-danger btn-sm", method: :delete, "data-confirm" => "本当に消しますか？"%><td>
                        <% end %>
                   </tr>
                  </tbody>
                 </table>

                  <div>
                   <%= link_to "削除", admin_study_path(@study), method: :delete, "data-confirm" => "本当に消しますか？" %>
                 </div>
        </div>
     </div>
  </div>
</div>